In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df =pd.read_csv("community_health.csv")
df.head()

age  gender race/ethnicity  weight  height  visits
0   47  female        group D     247      65      28
1   26    male        group C     283      66      23
2   26    male        group B     201      68      14
3   39    male        group C     237      73      21
4   55    male        group A     199      61      27

In [4]:
df.corr(numeric_only=True)

age    weight    height    visits
age     1.000000 -0.084920 -0.063822  0.539543
weight -0.084920  1.000000  0.142064  0.543139
height -0.063822  0.142064  1.000000 -0.385644
visits  0.539543  0.543139 -0.385644  1.000000

In [5]:
df.rename(columns={
        "age" : "yas",
        "gender" : "cinsiyet",
        "race/ethnicity" : "irk",
        "weight" : "kilo",
        "height" : "boy"

},inplace=True)

In [6]:
df.head()

yas cinsiyet      irk  kilo  boy  visits
0   47   female  group D   247   65      28
1   26     male  group C   283   66      23
2   26     male  group B   201   68      14
3   39     male  group C   237   73      21
4   55     male  group A   199   61      27

In [7]:
df["kilo"] = round(df["kilo"] * 0.45)

In [8]:
df["boy"] = round(df["boy"] * 2.54)

In [9]:
df.head()

yas cinsiyet      irk   kilo    boy  visits
0   47   female  group D  111.0  165.0      28
1   26     male  group C  127.0  168.0      23
2   26     male  group B   90.0  173.0      14
3   39     male  group C  107.0  185.0      21
4   55     male  group A   90.0  155.0      27

In [10]:
df["cinsiyet"].replace({
           "female" : 0,
           "male" : 1             
},inplace= True)

C:\Users\bilal\AppData\Local\Temp\ipykernel_35804\2797762072.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["cinsiyet"].replace({
C:\Users\bilal\AppData\Local\Temp\ipykernel_35804\2797762072.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["cinsiyet"].replace({


In [11]:
df.head()

yas  cinsiyet      irk   kilo    boy  visits
0   47         0  group D  111.0  165.0      28
1   26         1  group C  127.0  168.0      23
2   26         1  group B   90.0  173.0      14
3   39         1  group C  107.0  185.0      21
4   55         1  group A   90.0  155.0      27

In [12]:
df["irk"].replace({
       "group A" : 1,
       "group B" : 2,
       "group C" : 3,
       "group D" : 4,
       "group D" : 5,
       "group E" : 6                  
},inplace=True)

C:\Users\bilal\AppData\Local\Temp\ipykernel_35804\715775240.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["irk"].replace({
C:\Users\bilal\AppData\Local\Temp\ipykernel_35804\715775240.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["irk"].replace({


In [13]:
df.head()

yas  cinsiyet  irk   kilo    boy  visits
0   47         0    5  111.0  165.0      28
1   26         1    3  127.0  168.0      23
2   26         1    2   90.0  173.0      14
3   39         1    3  107.0  185.0      21
4   55         1    1   90.0  155.0      27

In [14]:
df.to_csv("community_health_MLR.csv",index=False)

In [15]:
X = df.drop("visits" , axis=1)
X

yas  cinsiyet  irk   kilo    boy
0     47         0    5  111.0  165.0
1     26         1    3  127.0  168.0
2     26         1    2   90.0  173.0
3     39         1    3  107.0  185.0
4     55         1    1   90.0  155.0
..   ...       ...  ...    ...    ...
995   43         0    6  123.0  173.0
996   34         0    5  111.0  193.0
997   54         0    2  140.0  190.0
998   38         1    6   29.0  190.0
999   62         0    5   96.0  170.0

[1000 rows x 5 columns]

In [16]:
y = df["visits"]
y

0      28
1      23
2      14
3      21
4      27
       ..
995    22
996    16
997    27
998     7
999    22
Name: visits, Length: 1000, dtype: int64

In [17]:
X.head()

yas  cinsiyet  irk   kilo    boy
0   47         0    5  111.0  165.0
1   26         1    3  127.0  168.0
2   26         1    2   90.0  173.0
3   39         1    3  107.0  185.0
4   55         1    1   90.0  155.0

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
regr = LinearRegression()

In [26]:
regr.fit(X,y)

LinearRegression()

In [27]:
y_hat = regr.predict(X)

In [29]:
regr.coef_

array([ 0.24628021,  0.097945  ,  0.03432211,  0.17710201, -0.18007208])

In [30]:
coaf_df = pd.DataFrame(regr.coef_ , X.columns , columns=["Katsayılar"])

In [31]:
coaf_df

Katsayılar
yas         0.246280
cinsiyet    0.097945
irk         0.034322
kilo        0.177102
boy        -0.180072

In [32]:
print(df["yas"].mean())
print(df["cinsiyet"].mean())
print(df["irk"].mean())
print(df["kilo"].mean())
print(df["boy"].mean())


45.019
0.481
3.552
89.574
170.914


In [33]:
her_hangi_bir_kisi = [[40,0,3,60,175]]

In [34]:
her_hangi_bir_kisi

[[40, 0, 3, 60, 175]]

In [36]:
regr.predict(her_hangi_bir_kisi)

c:\Users\bilal\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([12.68047284])

In [40]:
X.iloc[135]


yas          48.0
cinsiyet      1.0
irk           5.0
kilo        107.0
boy         180.0
Name: 135, dtype: float64

In [39]:
y.iloc[135]

np.int64(24)

In [42]:
diger_kisi = [[48,1,5,107,180]]
diger_kisi

[[48, 1, 5, 107, 180]]

In [43]:
regr.predict(diger_kisi)

c:\Users\bilal\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([22.24073788])

In [46]:
from joblib import dump ,load

In [47]:
dump(regr , "Dr_Hasta_1_.joblib")

['Dr_Hasta_1_.joblib']